### ISSUE TITLE
`-[SIWindow moveToSpace:]` Does not work on windows without toolbars

### ISSUE THREAD

**Issue by aaronlevin** [ianyh/Silica#12]
Feel free to close if this is a known issue, but my iTerm2 windows don't have a toolbar and this means I cannot `moveToSpace` with them. 

I'm not sure what the fix would be, but it might be worth porting over whatever `chunkwm` does because their move-to-space equivalent works fine on my system.

I believe the culprit is this code:

```
    // Move the mouse into place at the window's toolbar
    CGEventPost(kCGHIDEventTap, mouseMoveEvent);
    // Mouse down to grab hold of the window
    CGEventPost(kCGHIDEventTap, mouseDownEvent);
    // Send the shortcut command to get Mission Control to switch spaces from under the window.
    CGEventPost(kCGHIDEventTap, event.CGEvent);
    CGEventPost(kCGHIDEventTap, keyboardEventUp);
```

PS - thanks for Amethyst. I use it every day.

**Comment by ianyh** [comment]
Porting over chunkwm's mechanism is probably the right answer. The solution here is a bit hacky to get around using private APIs, but we started using private APIs elsewhere so we should just go for it here as well.

**Comment by ianyh** [comment]
The library uses private APIs now.
