### ISSUE TITLE
I wonder how i could do those things..

### ISSUE THREAD

**Issue by davibe** [ianyh/Silica#8]
1. how can i hide a window, not an app
2. how can i minimiza a window with no animation
3. how can i switch 'space' with no animation
4. how do i know wether a window is currently visible and focused 

I am trying to create a dock clone that is based on windows and windows groups instead of applications. So far I am a bit stuck with those things.

**Comment by ianyh** [comment]
1. Hiding is handled by macOS, and I think it's always an application level thing.
 2. Minimizing is also handled by macOS. The animation can be turned off in System Preferences, I think. There is possibly a private API mechanism for forcing it to not animate, but I don't know it.
 3. The way we hack together space transitions uses the macOS mechanism for switching spaces which is inherently animated. There are private APIs that I have not figured out yet.
 4. `-[SIWindow isActive]` will tell you if it is currently visible, and I usually compare it to `+[SIWindow focusedWindow]` to tell whether or not it is focused.
